FROM node:12-alpine

RUN apk update \
  && apk add --update alpine-sdk python \
  && yarn global add @angular/cli@9.1.6 \
  && apk del alpine-sdk python \
  && rm -rf /tmp/* /var/cache/apk/* *.tar.gz ~/.npm \
  && npm cache clean --force \
  && yarn cache clean \
  && sed -i -e "s/bin\/ash/bin\/sh/" /etc/passwd

ENV NODE_ENV=dev

WORKDIR /app/src
EXPOSE 5000

ENTRYPOINT npm run start:dev