name: Build and Test

on:
  pull_request:
    branches:
    - master
  workflow_call:
    
jobs:
  build-and-test:
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: docker/setup-buildx-action@v1
      
    - name: Build
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
